version: '3.7'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '8000:27017'
    volumes:
      - mongoMVP:/data/mvp
      - mongoMVP_config:/data/config_mvp
volumes:
  mongoMVP:
  mongoMVP_config:
